### PR TITLE
SYSIMG_PART_SZ // SELinux killer // Kernel options

### PR DESCRIPTION
**Pull request by InterfaceNode**
- BOARD_SYSTEMIMAGE_PARTITION_SIZE extrapolated by BLOCK_SIZE to closely match the actual output of system.img
- Add fall-back options for using proper pre-built kernel**
  *\* Proper hardware and kernel headers required, HTC uses pre-S3D display drivers so reverted or custom display fork will be required.
- Disable SELinux on boot (useful for testing Alpha builds)

### CODE REVIEW

**Comment by Rashed97** [comment]
Nice stuff, but sorry, can't merge this in its current form. No prebuilt kernel allowed. But that selinux disabled looks nice. (does it actually work? I mean doesn't 5.0 ban that?) And is that system partition size verified? (just trying to be thorough)

**Comment by InterfaceNode** [comment]
Yes, Datagutt and I have already begin building SlimROM alphas and are currently debugging it, system size is verified (when building output if it says "unable to fit X blocks" if left alone, you must multiply your blocks by this number to get a workable board size)

Our approach was slightly different, we unified everything into a single device folder for GSM and then began to configure the HW and build env based on what HTC had at the time they made their open-source kernel.

HTC has exported a lot of kernel operations to their build-env which is why things like sigcontext.h are broken out of the box when trying to build, they are moving their own versions of it to the OUT folder so this is kind of their way around releasing a kernel that can be used to just build firmware.

Your pre-built kernel does not work because HTC used display-caf drivers from before the S3D commits, so there is a header & HW confliction. 

They have also exported made changes in system/media (which someone else did before I pushed to Slim) and tinycompress; which the MSM8994 board needs and this small change can be found on my repo page.

With these build env changes and these HW configs this firmware will almost surely build in CyanogenMod as well!

I pushed this commit mostly as a substitute for PM, to let you know we exist~ Our unified Slim configs are undergoing steady revision and the ones up right now are not the same as what is being built with right now as we try prebuilt, and source-built kernel since both will build and generate a firmware under the HW we use

**Comment by InterfaceNode** [comment]
It can be disabled in 4.4/5.0/5.1

SELinux has 3 modes:
- Disabled
- Permissive
- Enforcing

SELinux is sometimes set 'hard' inside of the kernel and the only way to really disable it is to do so in the defconfigs; some devices have support for 'androidboot.selinux=permissive/enforcing/disabled' which lets you avoid messing around inside of kernel configs to disable it.

It was rare to see this in the 4.0 era because SE became required and not many folks were aware of how to use it, to build with SELinux disabled is the closest to true root you can get where things can execute without any accountability so while this is useful for testing..

ALSO for debugging I would highly suggest you turn off system.new.dat compression and have the firmware build in a traditional format; this can be done by going into:

build/core/Makefile

searching for "--block" and removing that entire line

**Comment by Rashed97** [comment]
Our kernel that we're building works perfectly (see the kernel_htc_msm8994 repo in Hima-Dev), stock boots up fine with it and the dt.img. Ramdisk is the problem now. It's been patched for sigcontext.h, SD3, and the min and max block size for audio. As for system/media, it's been patched in CM (I pushed that one) and so has tinycompress (I've been working on setting flags for it in the build system as to not break the other builds) Also, if you've gotten anything to boot (to the userspace), we'd love to see it. We're stuck at firmware links not being made now (me and Flinny, so the problem is both on CM and Slim). We also have a IRC channel up (#m9-dev) where we chat, so feel free to join. If you'll split this commit up, I'll go ahead and add you so you can push the system and selinux stuff directly, we just don't need the prebuilt kernel stuff anymore.

**Comment by InterfaceNode** [comment]
Our last build did not boot to userspace; it was highly impure and had many subsequent brunches

The latest build has a difference in size, env configs and a slightly different kernel (used pure pre-build as a test the first time) so I'm not positive about it; I must wait until it's tested

I suspect the purity of the build is fine, I imagine the issue here is in the build env itself like you said and I am in the process of comparing it to what HTC used

In the meantime I'll fork your configs and smash out a SlimROM with it and have it flashed & tested but I suspect MSM8994-CAFs droid branch contains the build env changes needed to finish this

I will clean my commits in this branch and repush something more friendly

**Comment by Rashed97** [comment]
Thx. I'll merge it as soon as I see it (going to bed no so that might be a
few hours)

**Comment by ardevd** [comment]
While setting SEAndroid to permissive makes sense from a testing and development perspective, I strongly oppose the notion that SEAndroid set to permissive has anything to do with  "true root" access. SEAndroid is a valuable security feature and should be set to enforced once all problematic AVC denials are dealt with.

Hopefully I just misunderstood you and the idea is simply to disable SEAndroid enforce during development and testing. :)

Just my 2 cents.

**Comment by Tquet** [comment]
You're wrong Zyg0te but it is ok

**Pull request closed without merging**
